############################################################
# Dockerfile to deploy jar using alpine image
############################################################
FROM nginx:alpine

# Maintainer
MAINTAINER "sudheer veeravalli <veersudhir83@gmail.com>"

# Copy war file to tomcat webapps folder
COPY . /usr/share/nginx/html